### ISSUE TITLE
Créer le script de backup (OSP)

### ISSUE THREAD

**Issue by pierreozoux** [OpenSourcePolitics/k8s-decidim-operator#1]
Alain a déjà une procédure de backup:
 - dump bdd
 - fichiers uploadés
 - config (yaml/json)
   - vérifier que config vide (à part redis, s3, bdd...)
   - SECRET_KEY_BASE à transférer aussi
   - sinon, transférer config dans kube (.i.e FranceConnect, ou autre)
 - commit hash
   - push image docker avec commit hash
   - s'assurer que l'image docker est bien présente, et que la version sera la même au départ et à l'arrivée.

```
database/
  *.sql
objects/
kubernetes/
  decidim.yml 
    domain:
    image: registry:commit_hash
  secret.yml (! name)
  cm.yml (! name)
```

In fine cette tar ball doit se trouver sur une URL.
(Genre bucket scaleway).

**Comment by armandfardeau** [comment]
objects -> objects contenu dans l'objects store

**Comment by armandfardeau** [comment]
Ajouter variable d'environnement

**Comment by pierreozoux** [comment]
Proposition de format pour l'archive:

```
database/
  *.sql
objects/
metadata.yml
  config:
    ENV_VAR: env
  domaine: org.fr
  image: registry:commit_hash
```

Dans le cas idéal, les instances sont déjà sur un ObjectStorage. Et nous migrons du compte OSP vers le compte IndieHosters.

Si cela est difficile, il est possile d'envisager la migration local -> object store pendant la migration.

**Comment by pierreozoux** [comment]
Alain nous livre un env de test milieu semaine prochaine.

**Comment by pierreozoux** [comment]
déplacé ici:
https://forge.liiib.re/libre.sh/clusters-osp/-/issues/7
