### ISSUE TITLE
Script Orienter traffic nginx -> k8s (2j) (w8)

### ISSUE THREAD

**Issue by pierreozoux** [OpenSourcePolitics/k8s-decidim-operator#7]

**Comment by armandfardeau** [comment]
Piste: https://www.scaleway.com/en/docs/tutorials/nginx-reverse-proxy/#nginx-reverse-proxy-example-configuration

**Comment by pierreozoux** [comment]
@moustachu tu pourras me donner accès ssh à une VM de test?

merci!

**Comment by pierreozoux** [comment]
accès donné.

**Comment by pierreozoux** [comment]
bougé ici: https://forge.liiib.re/libre.sh/clusters-osp/-/issues/2
